[workspace]
resolver = "2"
members = [
    "crates/vifei-core",
    "crates/vifei-import",
    "crates/vifei-export",
    "crates/vifei-tui",
    "crates/vifei-tour",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
