[package]
name = "vifei-import"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vifei-core = { path = "../vifei-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
tempfile = "3"
